### ISSUE TITLE
2.9.x Beta Bugs / Roadmap

### ISSUE THREAD

**Issue by JosXa** [johnlindquist/kit#1483]
### Critical Bugs
(in order of priority)

1. [ ] Replace key/mouse automation library
2. [ ] `open` calls completely broken
3. [ ] Widgets completely broken: They open in the top right, show "Missing body", and behave weirdly when resizing.
4. [ ] Network permissions screen on Windows when installing the app
5. [ ] `lstat` problem when Emojis in the filename (PR is open)
6. [ ] Resizing snaps back: https://discord.com/channels/804053880266686464/1149451928556814366/1239341891565129851
7. [ ] `debounceInput` on editor debounces, but then fires the inputs for all characters at once.**
8. [ ] After an `await run("sub-script")`, the parent script does not continue execution.

### Improvements
- [ ] Usually, you **right** click taskbar icons on Windows, not **left**.
